package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class AcctRecordProject extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_record_project.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_record_project.ACCT_RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String acctRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_record_project.PROJECT_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_record_project.PROJECT_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_record_project.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_record_project.RECORD_ID
     *
     * @return the value of acct_record_project.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_record_project.RECORD_ID
     *
     * @param recordId the value for acct_record_project.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_record_project.ACCT_RECORD_ID
     *
     * @return the value of acct_record_project.ACCT_RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getAcctRecordId() {
        return acctRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_record_project.ACCT_RECORD_ID
     *
     * @param acctRecordId the value for acct_record_project.ACCT_RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setAcctRecordId(String acctRecordId) {
        this.acctRecordId = acctRecordId == null ? null : acctRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_record_project.PROJECT_ID
     *
     * @return the value of acct_record_project.PROJECT_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_record_project.PROJECT_ID
     *
     * @param projectId the value for acct_record_project.PROJECT_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_record_project.PROJECT_NAME
     *
     * @return the value of acct_record_project.PROJECT_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_record_project.PROJECT_NAME
     *
     * @param projectName the value for acct_record_project.PROJECT_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_record_project.REMARK
     *
     * @return the value of acct_record_project.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_record_project.REMARK
     *
     * @param remark the value for acct_record_project.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", acctRecordId=").append(acctRecordId);
        sb.append(", projectId=").append(projectId);
        sb.append(", projectName=").append(projectName);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}