package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class CustFriend extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.FRIEND_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.GENDER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.MOBILE_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.DATE_REG
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String dateReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.FLAG_DELETED
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String flagDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.FRIEND_ID
     *
     * @return the value of cust_friend.FRIEND_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.FRIEND_ID
     *
     * @param friendId the value for cust_friend.FRIEND_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.CUST_NO
     *
     * @return the value of cust_friend.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.CUST_NO
     *
     * @param custNo the value for cust_friend.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.NAME
     *
     * @return the value of cust_friend.NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.NAME
     *
     * @param name the value for cust_friend.NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.GENDER
     *
     * @return the value of cust_friend.GENDER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.GENDER
     *
     * @param gender the value for cust_friend.GENDER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.MOBILE_NO
     *
     * @return the value of cust_friend.MOBILE_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.MOBILE_NO
     *
     * @param mobileNo the value for cust_friend.MOBILE_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.DATE_REG
     *
     * @return the value of cust_friend.DATE_REG
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getDateReg() {
        return dateReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.DATE_REG
     *
     * @param dateReg the value for cust_friend.DATE_REG
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setDateReg(String dateReg) {
        this.dateReg = dateReg == null ? null : dateReg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.FLAG_DELETED
     *
     * @return the value of cust_friend.FLAG_DELETED
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getFlagDeleted() {
        return flagDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.FLAG_DELETED
     *
     * @param flagDeleted the value for cust_friend.FLAG_DELETED
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setFlagDeleted(String flagDeleted) {
        this.flagDeleted = flagDeleted == null ? null : flagDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend.REMARK
     *
     * @return the value of cust_friend.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend.REMARK
     *
     * @param remark the value for cust_friend.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", friendId=").append(friendId);
        sb.append(", custNo=").append(custNo);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", mobileNo=").append(mobileNo);
        sb.append(", dateReg=").append(dateReg);
        sb.append(", flagDeleted=").append(flagDeleted);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}