package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class CustCTagFriend extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_c_tag_friend.TAG_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_c_tag_friend.TAG_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_c_tag_friend.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_c_tag_friend.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_c_tag_friend.TAG_ID
     *
     * @return the value of cust_c_tag_friend.TAG_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_c_tag_friend.TAG_ID
     *
     * @param tagId the value for cust_c_tag_friend.TAG_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_c_tag_friend.TAG_NAME
     *
     * @return the value of cust_c_tag_friend.TAG_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_c_tag_friend.TAG_NAME
     *
     * @param tagName the value for cust_c_tag_friend.TAG_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_c_tag_friend.CUST_NO
     *
     * @return the value of cust_c_tag_friend.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_c_tag_friend.CUST_NO
     *
     * @param custNo the value for cust_c_tag_friend.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_c_tag_friend.REMARK
     *
     * @return the value of cust_c_tag_friend.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_c_tag_friend.REMARK
     *
     * @param remark the value for cust_c_tag_friend.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tagId=").append(tagId);
        sb.append(", tagName=").append(tagName);
        sb.append(", custNo=").append(custNo);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}