package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class CustInfo extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.WX_OPENID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.DATE_REGISTER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String dateRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.MAX_FRIEND_CNT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private Integer maxFriendCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.MAX_RECORD_CNT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private Integer maxRecordCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_info.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.CUST_NO
     *
     * @return the value of cust_info.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.CUST_NO
     *
     * @param custNo the value for cust_info.CUST_NO
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.WX_OPENID
     *
     * @return the value of cust_info.WX_OPENID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.WX_OPENID
     *
     * @param wxOpenid the value for cust_info.WX_OPENID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.DATE_REGISTER
     *
     * @return the value of cust_info.DATE_REGISTER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getDateRegister() {
        return dateRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.DATE_REGISTER
     *
     * @param dateRegister the value for cust_info.DATE_REGISTER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setDateRegister(String dateRegister) {
        this.dateRegister = dateRegister == null ? null : dateRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.MAX_FRIEND_CNT
     *
     * @return the value of cust_info.MAX_FRIEND_CNT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public Integer getMaxFriendCnt() {
        return maxFriendCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.MAX_FRIEND_CNT
     *
     * @param maxFriendCnt the value for cust_info.MAX_FRIEND_CNT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setMaxFriendCnt(Integer maxFriendCnt) {
        this.maxFriendCnt = maxFriendCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.MAX_RECORD_CNT
     *
     * @return the value of cust_info.MAX_RECORD_CNT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public Integer getMaxRecordCnt() {
        return maxRecordCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.MAX_RECORD_CNT
     *
     * @param maxRecordCnt the value for cust_info.MAX_RECORD_CNT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setMaxRecordCnt(Integer maxRecordCnt) {
        this.maxRecordCnt = maxRecordCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_info.REMARK
     *
     * @return the value of cust_info.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_info.REMARK
     *
     * @param remark the value for cust_info.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custNo=").append(custNo);
        sb.append(", wxOpenid=").append(wxOpenid);
        sb.append(", dateRegister=").append(dateRegister);
        sb.append(", maxFriendCnt=").append(maxFriendCnt);
        sb.append(", maxRecordCnt=").append(maxRecordCnt);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}