package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class CustFriendTag extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend_tag.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend_tag.FRIEND_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend_tag.TAG_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend_tag.TAG_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_friend_tag.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend_tag.RECORD_ID
     *
     * @return the value of cust_friend_tag.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend_tag.RECORD_ID
     *
     * @param recordId the value for cust_friend_tag.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend_tag.FRIEND_ID
     *
     * @return the value of cust_friend_tag.FRIEND_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend_tag.FRIEND_ID
     *
     * @param friendId the value for cust_friend_tag.FRIEND_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend_tag.TAG_ID
     *
     * @return the value of cust_friend_tag.TAG_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend_tag.TAG_ID
     *
     * @param tagId the value for cust_friend_tag.TAG_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend_tag.TAG_NAME
     *
     * @return the value of cust_friend_tag.TAG_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend_tag.TAG_NAME
     *
     * @param tagName the value for cust_friend_tag.TAG_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_friend_tag.REMARK
     *
     * @return the value of cust_friend_tag.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_friend_tag.REMARK
     *
     * @param remark the value for cust_friend_tag.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", friendId=").append(friendId);
        sb.append(", tagId=").append(tagId);
        sb.append(", tagName=").append(tagName);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}