package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class PubDomainValuesKey extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_domain_values.CODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_domain_values.VALUE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_domain_values.CODE
     *
     * @return the value of pub_domain_values.CODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_domain_values.CODE
     *
     * @param code the value for pub_domain_values.CODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_domain_values.VALUE
     *
     * @return the value of pub_domain_values.VALUE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_domain_values.VALUE
     *
     * @param value the value for pub_domain_values.VALUE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}