package com.tts.xiaoliji.common.dao.mybatis.dto;

import java.io.Serializable;

public class PubDomainValues extends PubDomainValuesKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_domain_values.TEXT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_domain_values.SEQ
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_domain_values.STATUS
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_domain_values.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_domain_values.TEXT
     *
     * @return the value of pub_domain_values.TEXT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_domain_values.TEXT
     *
     * @param text the value for pub_domain_values.TEXT
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_domain_values.SEQ
     *
     * @return the value of pub_domain_values.SEQ
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_domain_values.SEQ
     *
     * @param seq the value for pub_domain_values.SEQ
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_domain_values.STATUS
     *
     * @return the value of pub_domain_values.STATUS
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_domain_values.STATUS
     *
     * @param status the value for pub_domain_values.STATUS
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_domain_values.REMARK
     *
     * @return the value of pub_domain_values.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_domain_values.REMARK
     *
     * @param remark the value for pub_domain_values.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", text=").append(text);
        sb.append(", seq=").append(seq);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}