package com.tts.xiaoliji.common.dao.mybatis.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class WxLoginLog extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.OPENID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.UNIONID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.SESSION_KEY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.JS_CODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String jsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.NICK_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.AVATAR_URL
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.GENDER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.CITY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.PROVINCE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.COUNTRY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.LANGUAGE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.WX_ERRCODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String wxErrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.WX_ERRMSG
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String wxErrmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_login_log.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_login_log
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.RECORD_ID
     *
     * @return the value of wx_login_log.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.RECORD_ID
     *
     * @param recordId the value for wx_login_log.RECORD_ID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.OPENID
     *
     * @return the value of wx_login_log.OPENID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.OPENID
     *
     * @param openid the value for wx_login_log.OPENID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.UNIONID
     *
     * @return the value of wx_login_log.UNIONID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.UNIONID
     *
     * @param unionid the value for wx_login_log.UNIONID
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.SESSION_KEY
     *
     * @return the value of wx_login_log.SESSION_KEY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.SESSION_KEY
     *
     * @param sessionKey the value for wx_login_log.SESSION_KEY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.JS_CODE
     *
     * @return the value of wx_login_log.JS_CODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getJsCode() {
        return jsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.JS_CODE
     *
     * @param jsCode the value for wx_login_log.JS_CODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setJsCode(String jsCode) {
        this.jsCode = jsCode == null ? null : jsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.NICK_NAME
     *
     * @return the value of wx_login_log.NICK_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.NICK_NAME
     *
     * @param nickName the value for wx_login_log.NICK_NAME
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.AVATAR_URL
     *
     * @return the value of wx_login_log.AVATAR_URL
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.AVATAR_URL
     *
     * @param avatarUrl the value for wx_login_log.AVATAR_URL
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.GENDER
     *
     * @return the value of wx_login_log.GENDER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.GENDER
     *
     * @param gender the value for wx_login_log.GENDER
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.CITY
     *
     * @return the value of wx_login_log.CITY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.CITY
     *
     * @param city the value for wx_login_log.CITY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.PROVINCE
     *
     * @return the value of wx_login_log.PROVINCE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.PROVINCE
     *
     * @param province the value for wx_login_log.PROVINCE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.COUNTRY
     *
     * @return the value of wx_login_log.COUNTRY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.COUNTRY
     *
     * @param country the value for wx_login_log.COUNTRY
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.LANGUAGE
     *
     * @return the value of wx_login_log.LANGUAGE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.LANGUAGE
     *
     * @param language the value for wx_login_log.LANGUAGE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.WX_ERRCODE
     *
     * @return the value of wx_login_log.WX_ERRCODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getWxErrcode() {
        return wxErrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.WX_ERRCODE
     *
     * @param wxErrcode the value for wx_login_log.WX_ERRCODE
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setWxErrcode(String wxErrcode) {
        this.wxErrcode = wxErrcode == null ? null : wxErrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.WX_ERRMSG
     *
     * @return the value of wx_login_log.WX_ERRMSG
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getWxErrmsg() {
        return wxErrmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.WX_ERRMSG
     *
     * @param wxErrmsg the value for wx_login_log.WX_ERRMSG
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setWxErrmsg(String wxErrmsg) {
        this.wxErrmsg = wxErrmsg == null ? null : wxErrmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_login_log.REMARK
     *
     * @return the value of wx_login_log.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_login_log.REMARK
     *
     * @param remark the value for wx_login_log.REMARK
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_login_log
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", openid=").append(openid);
        sb.append(", unionid=").append(unionid);
        sb.append(", sessionKey=").append(sessionKey);
        sb.append(", jsCode=").append(jsCode);
        sb.append(", nickName=").append(nickName);
        sb.append(", avatarUrl=").append(avatarUrl);
        sb.append(", gender=").append(gender);
        sb.append(", city=").append(city);
        sb.append(", province=").append(province);
        sb.append(", country=").append(country);
        sb.append(", language=").append(language);
        sb.append(", wxErrcode=").append(wxErrcode);
        sb.append(", wxErrmsg=").append(wxErrmsg);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}