package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.AcctRecordProject;
import com.tts.xiaoliji.common.dao.mybatis.dto.AcctRecordProjectCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcctRecordProjectMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(AcctRecordProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(AcctRecordProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(AcctRecordProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(AcctRecordProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<AcctRecordProject> selectByExample(AcctRecordProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    AcctRecordProject selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") AcctRecordProject record, @Param("example") AcctRecordProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") AcctRecordProject record, @Param("example") AcctRecordProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(AcctRecordProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record_project
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(AcctRecordProject record);
}