package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.AcctRecord;
import com.tts.xiaoliji.common.dao.mybatis.dto.AcctRecordCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcctRecordMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String acctRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(AcctRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(AcctRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<AcctRecord> selectByExampleWithBLOBs(AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<AcctRecord> selectByExample(AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    AcctRecord selectByPrimaryKey(String acctRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") AcctRecord record, @Param("example") AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AcctRecord record, @Param("example") AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") AcctRecord record, @Param("example") AcctRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(AcctRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AcctRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_record
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(AcctRecord record);
}