package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustCTagFriend;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustCTagFriendCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustCTagFriendMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(CustCTagFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(CustCTagFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(CustCTagFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(CustCTagFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<CustCTagFriend> selectByExample(CustCTagFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    CustCTagFriend selectByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustCTagFriend record, @Param("example") CustCTagFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") CustCTagFriend record, @Param("example") CustCTagFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(CustCTagFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_c_tag_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(CustCTagFriend record);
}