package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustFriendTag;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustFriendTagCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustFriendTagMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(CustFriendTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(CustFriendTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(CustFriendTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(CustFriendTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<CustFriendTag> selectByExample(CustFriendTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    CustFriendTag selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustFriendTag record, @Param("example") CustFriendTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") CustFriendTag record, @Param("example") CustFriendTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(CustFriendTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend_tag
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(CustFriendTag record);
}