package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustInfo;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustInfoMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(CustInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(CustInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(CustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(CustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<CustInfo> selectByExample(CustInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    CustInfo selectByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustInfo record, @Param("example") CustInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") CustInfo record, @Param("example") CustInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(CustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_info
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(CustInfo record);
}