package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustFriend;
import com.tts.xiaoliji.common.dao.mybatis.dto.CustFriendCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustFriendMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(CustFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(CustFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(CustFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(CustFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<CustFriend> selectByExample(CustFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    CustFriend selectByPrimaryKey(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustFriend record, @Param("example") CustFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") CustFriend record, @Param("example") CustFriendCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(CustFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_friend
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(CustFriend record);
}