package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.PubDomainValues;
import com.tts.xiaoliji.common.dao.mybatis.dto.PubDomainValuesCriteria;
import com.tts.xiaoliji.common.dao.mybatis.dto.PubDomainValuesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PubDomainValuesMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(PubDomainValuesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(PubDomainValuesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(PubDomainValuesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(PubDomainValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(PubDomainValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<PubDomainValues> selectByExample(PubDomainValuesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    PubDomainValues selectByPrimaryKey(PubDomainValuesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") PubDomainValues record, @Param("example") PubDomainValuesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") PubDomainValues record, @Param("example") PubDomainValuesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(PubDomainValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain_values
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(PubDomainValues record);
}