package com.tts.xiaoliji.common.dao.mybatis.client;

import cn.openlo.dataobject.DAO;
import com.tts.xiaoliji.common.dao.mybatis.dto.PubDomain;
import com.tts.xiaoliji.common.dao.mybatis.dto.PubDomainCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PubDomainMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int countByExample(PubDomainCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByExample(PubDomainCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insert(PubDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int insertSelective(PubDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    List<PubDomain> selectByExample(PubDomainCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    PubDomain selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") PubDomain record, @Param("example") PubDomainCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByExample(@Param("record") PubDomain record, @Param("example") PubDomainCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKeySelective(PubDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_domain
     *
     * @mbggenerated Fri Jan 26 17:54:01 CST 2018
     */
    int updateByPrimaryKey(PubDomain record);
}